replicaCount: 1

image:
  repository: nekoneko/goflippy-api
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 0.0.0.0/0
  loadBalancerIPEnabled: false
  loadBalancerIP: 0.0.0.0
  annotations: {}

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - goflippy.api.local
  tls:
    # - goflippy.api.local

env:
  STORE_TIMEOUT_SECONDS: 30
  STORE_ADDRS: mongo
  STORE_DB: goflippy

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
