version: "3.3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - .:/go/src/github.com/neko-neko/goflippy
    ports:
      - 9000:9000
    links:
      - mongo
    environment:
      DEBUG: "true"
      STORE_ADDRS: "mongo"
      STORE_DB: "goflippy"
    env_file: api/.env
  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    volumes:
      - .:/go/src/github.com/neko-neko/goflippy
    ports:
      - 9001:9001
    links:
      - mongo
    environment:
      DEBUG: "true"
      STORE_ADDRS: "mongo"
      STORE_DB: "goflippy"
    env_file: admin/.env
  admin-ui:
    build:
      context: ./admin-ui/
    volumes:
      - ./admin-ui/:/app
      - /app/node_modules
    ports:
      - 8080:8080
    links:
      - admin
  mongo:
    image: mongo:3.6
    volumes:
      - store-data:/data/db
    ports:
      - 27017:27017
  mongo-admin:
    image: mongo-express:0.49
    ports:
      - 18081:8081
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
volumes:
  store-data:
    driver: local
