FROM golang:1.11 as builder

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

WORKDIR /go/src/github.com/neko-neko/goflippy
COPY . .
RUN make build-api

FROM alpine:3.8
EXPOSE 9001

ENV GODEBUG=netdns=go

RUN mkdir /app && \
    apk add -U --no-cache ca-certificates tzdata
COPY --from=builder /go/src/github.com/neko-neko/goflippy/release/linux/amd64/goflippy-api /app
CMD ["/app/goflippy-api"]
