version: "3.3"
services:
  api:
    build:
      context: api/
    volumes:
      - .:/go/src/app
    ports:
      - 9000:9000
    links:
      - mongo
    environment:
      DEBUG: "true"
      PORT: "8080"
      STOREURL: "mongodb://mongo"
      DB: "goflippy"
    env_file: api/.env
  mongo:
    image: mongo:3.6
    volumes:
      - store-data:/data/db
    ports:
      - 27017:27017
  mongo-admin:
    image: mongo-express:0.49
    ports:
      - 18081:8081
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
volumes:
  store-data:
    driver: local
