version: 2
jobs:
  build:
    docker:
      - image: golang:1.11
      - image: mongo:3.6
    working_directory: /go/src/github.com/neko-neko/goflippy
    steps:
      - checkout
      - run:
          name: Run tests
          command: make test-ci
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Build API server
          command: make setup && make build-api
      - run:
          name: Run API server
          command: release/linux/amd64/goflippy-api
          background: true
          environment:
            DEBUG: "true"
            STORE_ADDRS: "localhost:27017"
            STORE_DB: "goflippy"
      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for API server
          command: dockerize -wait tcp://localhost:9000 -timeout 1m
      - run:
          name: Verify api server is working
          command: curl --retry 10 --retry-delay 1 http://localhost:9000
      - run:
          name: Build Admin server
          command: make setup && make build-admin
      - run:
          name: Run Admin server
          command: release/linux/amd64/goflippy-admin
          background: true
          environment:
            DEBUG: "true"
            STORE_ADDRS: "localhost:27017"
            STORE_DB: "goflippy"
      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for Admin server
          command: dockerize -wait tcp://localhost:9001 -timeout 1m
      - run:
          name: Verify admin server is working
          command: curl --retry 10 --retry-delay 1 http://localhost:9001
