apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    app: {{ include "api.name" . }}
    chart: {{ include "api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9000
  selector:
    app: {{ include "api.name" . }}
    release: {{ .Release.Name }}
  {{ if eq .Values.service.type "LoadBalancer" -}}
  loadBalancerSourceRanges: {{ .Values.service.loadBalancerSourceRanges }}
  {{ if .Values.service.loadBalancerIPEnabled -}}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end -}}
  {{- end -}}
